package ai.liquid.leap.function.pythonic

/**
 * Tokenizer to tokenize Pythonic function call code generated by the model.
 *
 * It is used by [PythonicParser] and it should not be used directly by the external code.
 */
class PythonicTokenizer(private val buffer: String) : Iterable<PythonicToken> {
  private var nextPos: Int = 0

  val hasNextToken: Boolean
    get() = nextPos < buffer.length

  val currentPosition: Int
    get() = nextPos

  @Throws(PythonicSyntaxError::class)
  fun nextToken(): PythonicToken? {
    if (nextPos == buffer.length) {
      return null
    }
    return when (buffer[nextPos]) {
      '[' -> {
        nextPos += 1
        PythonicToken(PythonicTokenName.LEFT_SQUARE_BRACKET, "[")
      }
      ']' -> {
        nextPos += 1
        PythonicToken(PythonicTokenName.RIGHT_SQUARE_BRACKET, "]")
      }
      '(' -> {
        nextPos += 1
        PythonicToken(PythonicTokenName.LEFT_PARENTHESES, "(")
      }
      ')' -> {
        nextPos += 1
        PythonicToken(PythonicTokenName.RIGHT_PARENTHESES, ")")
      }
      '{' -> {
        nextPos += 1
        PythonicToken(PythonicTokenName.LEFT_CURLY_BRACKET, "{")
      }
      '}' -> {
        nextPos += 1
        PythonicToken(PythonicTokenName.RIGHT_CURLY_BRACKET, "}")
      }
      ':' -> {
        nextPos += 1
        PythonicToken(PythonicTokenName.COLON, ":")
      }
      ',' -> {
        nextPos += 1
        PythonicToken(PythonicTokenName.COMMA, ",")
      }
      '=' -> {
        nextPos += 1
        PythonicToken(PythonicTokenName.EQUAL, "=")
      }
      ' ',
      '\t',
      '\n' -> {
        val spaceText = StringBuilder()
        while (nextPos < buffer.length) {
          when (buffer[nextPos]) {
            ' ',
            '\t',
            '\n' -> {
              spaceText.append(buffer[nextPos])
            }
            else -> {
              break
            }
          }
          nextPos += 1
        }
        PythonicToken(PythonicTokenName.SPACE, spaceText.toString())
      }
      in 'a'..'z',
      in 'A'..'Z' -> {
        val identifier = StringBuilder()
        while (nextPos < buffer.length) {
          when (buffer[nextPos]) {
            in 'a'..'z',
            in 'A'..'Z',
            in '0'..'9',
            '_' -> {
              identifier.append(buffer[nextPos])
            }
            else -> {
              break
            }
          }
          nextPos += 1
        }
        return PythonicToken(PythonicTokenName.IDENTIFIER, identifier.toString())
      }
      in '0'..'9',
      '+',
      '-',
      '.' -> {
        val numberLiteral = StringBuilder()
        var dotFound = buffer[nextPos] == '.'
        numberLiteral.append(buffer[nextPos])
        nextPos += 1
        while (nextPos < buffer.length) {
          when (buffer[nextPos]) {
            in '0'..'9' -> {
              numberLiteral.append(buffer[nextPos])
            }
            '.' -> {
              if (dotFound) {
                throw PythonicSyntaxError(nextPos, "Multiple dots in number literal")
              } else {
                dotFound = true
                numberLiteral.append(buffer[nextPos])
              }
            }
            else -> {
              break
            }
          }
          nextPos += 1
        }
        PythonicToken(PythonicTokenName.NUMBER_LITERAL, numberLiteral.toString())
      }
      '"',
      '\'' -> {
        val stringLiteral = StringBuilder()
        var isEscaping = false
        val quote = buffer[nextPos]
        nextPos += 1
        while (nextPos < buffer.length) {
          when (buffer[nextPos]) {
            '\\' -> {
              if (!isEscaping) {
                isEscaping = true
              } else {
                isEscaping = false
                stringLiteral.append('\\')
              }
            }
            quote -> {
              if (isEscaping) {
                stringLiteral.append(quote)
                isEscaping = false
              } else {
                break
              }
            }
            else -> {
              stringLiteral.append(buffer[nextPos])
            }
          }
          nextPos += 1
        }
        if (nextPos == buffer.length || buffer[nextPos] != quote) {
          throw PythonicSyntaxError(nextPos, "LeapStr literal not finished")
        }
        // When the loop ends correctly, buffer[nextPos] is the ending quote.
        // We hence need to advance the nextPos
        nextPos += 1
        PythonicToken(PythonicTokenName.STRING_LITERAL, stringLiteral.toString())
      }
      else -> {
        throw PythonicSyntaxError(nextPos, "Unknown token")
      }
    }
  }

  override fun iterator(): Iterator<PythonicToken> =
    object : Iterator<PythonicToken> {
      override fun next(): PythonicToken =
        this@PythonicTokenizer.nextToken()
          ?: throw NoSuchElementException(
            "No more tokens to iterate at position $nextPos in buffer of length ${buffer.length}"
          )

      override fun hasNext(): Boolean = this@PythonicTokenizer.hasNextToken
    }
}
