package ai.liquid.leap.function.pythonic

import ai.liquid.leap.LeapThrows
import ai.liquid.leap.function.LeapFunctionCall

/**
 * Parser for Pythonic tool call requests generated by the models. Details of the Pythonic tool call
 * format can be found at
 * https://docs.vllm.ai/en/latest/features/tool_calling.html#models-with-pythonic-tool-calls-pythonic
 *
 * Supported features are:
 * 1. A list of function call
 * 2. Named parameters
 * 3. LeapStr, number (int and double), boolean and null as primitive types
 * 4. Nested lists and objects of any types as parameters
 */
class PythonicParser(buffer: String) {
  private val tokens = PythonicTokenizer(buffer).asSequence().toList().toTypedArray()
  private var tokenPosition = 0
  private var textPosition = 0

  /**
   * Parse the Pythonic function call requests and return a list of [LeapFunctionCall] objects as
   * the result.
   *
   * This function can only be called once because it will mutate the parser internal states.
   */
  @LeapThrows(PythonicSyntaxError::class)
  fun parsePythonicCalls(): List<LeapFunctionCall> {
    val calls = mutableListOf<LeapFunctionCall>()
    expectToken(PythonicTokenName.LEFT_SQUARE_BRACKET)
    while (tokenPosition < tokens.size) {
      val functionNameIdentifier = expectToken(PythonicTokenName.IDENTIFIER)
      expectToken(PythonicTokenName.LEFT_PARENTHESES)
      val parameters = mutableMapOf<String, Any?>()
      // parse parameter list
      while (tokenPosition < tokens.size) {
        when (nextTokenNameOrException()) {
          PythonicTokenName.SPACE -> {
            moveToNextToken()
          }
          PythonicTokenName.IDENTIFIER -> {
            val parameterNameValuePair = expectIdentifierEqualValueClause()
            parameters.put(parameterNameValuePair.first, parameterNameValuePair.second)
            tryConsumeComma()
          }
          PythonicTokenName.RIGHT_PARENTHESES -> {
            // reach end of function call, emit a result
            moveToNextToken()
            break
          }
          else -> {
            throw PythonicSyntaxError(textPosition, "Unexpected token: ${tokens[tokenPosition]}")
          }
        }
      }
      calls.add(LeapFunctionCall(functionNameIdentifier.text, parameters))
      tryConsumeSpace()

      // next token should be right square bracket OR comma
      when (nextTokenNameOrException()) {
        PythonicTokenName.RIGHT_SQUARE_BRACKET -> {
          // end of function call list.
          break
        }
        PythonicTokenName.COMMA -> {
          // could be another function call, or the end of function call
          moveToNextToken()
          tryConsumeSpace()
          if (tokens[tokenPosition].name == PythonicTokenName.RIGHT_SQUARE_BRACKET) {
            // End with ",]"
            break
          }
        }
        else -> {
          throw PythonicSyntaxError(textPosition, "Unexpected token ${tokens[tokenPosition]}")
        }
      }
    }
    return calls
  }

  /** Move the pointer to next token. It should be called once the current token is consumed. */
  private fun moveToNextToken() {
    val currentToken = tokens[tokenPosition]
    textPosition += currentToken.text.length
    // text field of the LeapStr literal doesn't contains the quote marks, which should be counted
    if (currentToken.name == PythonicTokenName.STRING_LITERAL) {
      textPosition += 2
    }
    tokenPosition += 1
  }

  /**
   * Expect the next token to be a certain type of tokens. If the expected token arrives, consume
   * and return it; otherwise, throw an exception.
   *
   * @param tokenName the token name to expect
   * @param ignoreSpace if it is true, all space tokens will be consumed and ignored.
   */
  @LeapThrows(PythonicSyntaxError::class)
  private fun expectToken(
    tokenName: PythonicTokenName,
    ignoreSpace: Boolean = true,
  ): PythonicToken {
    if (ignoreSpace && tokenName == PythonicTokenName.SPACE) {
      throw PythonicSyntaxError(textPosition, "Expect $tokenName but also try to ignore spaces!")
    }
    while (true) {
      val nextToken =
        tokens.getOrNull(tokenPosition)
          ?: throw PythonicSyntaxError(textPosition, "Expect $tokenName, but the input ends")
      if (ignoreSpace && nextToken.name == PythonicTokenName.SPACE) {
        moveToNextToken()
        continue
      }
      if (nextToken.name == tokenName) {
        moveToNextToken()
        return nextToken
      } else {
        throw PythonicSyntaxError(textPosition, "Expect $tokenName, but found $nextToken")
      }
    }
  }

  /**
   * Expect and capture a clause of "IDENTIFIER = VALUE"
   *
   * @return a pair of the identifier string and the value
   */
  @LeapThrows(PythonicSyntaxError::class)
  private fun expectIdentifierEqualValueClause(): Pair<String, Any?> {
    val identifierToken = expectToken(PythonicTokenName.IDENTIFIER)
    expectToken(PythonicTokenName.EQUAL)
    val value = captureValue()
    return Pair(identifierToken.text, value)
  }

  /** If the next token is a comma, consume it. Otherwise do nothing. */
  private fun tryConsumeComma() {
    val token = tokens.getOrNull(tokenPosition) ?: return
    if (token.name == PythonicTokenName.COMMA) {
      moveToNextToken()
    }
  }

  /** If the next token is a space, consume it. Otherwise do nothing. */
  private fun tryConsumeSpace() {
    val token = tokens.getOrNull(tokenPosition) ?: return
    if (token.name == PythonicTokenName.SPACE) {
      moveToNextToken()
    }
  }

  /** Capture a value literal and return it. */
  @LeapThrows(PythonicSyntaxError::class)
  private fun captureValue(): Any? {
    tryConsumeSpace()
    val startPos = textPosition
    val valueToken =
      tokens.getOrNull(tokenPosition)
        ?: throw PythonicSyntaxError(startPos, "Expect a value, but the input ends")
    moveToNextToken()
    when (valueToken.name) {
      PythonicTokenName.NUMBER_LITERAL -> {
        val numberText = valueToken.text
        return if (numberText.contains('.')) {
          numberText.toDouble()
        } else {
          numberText.toInt()
        }
      }
      PythonicTokenName.STRING_LITERAL -> {
        return valueToken.text
      }
      PythonicTokenName.IDENTIFIER -> {
        return when (valueToken.text) {
          "true",
          "True" -> true
          "false",
          "False" -> false
          "null",
          "None" -> null
          else -> throw PythonicSyntaxError(startPos, "Expect a value, but found $valueToken")
        }
      }
      PythonicTokenName.LEFT_SQUARE_BRACKET -> {
        // list type
        val result = mutableListOf<Any?>()
        while (true) {
          tryConsumeSpace()
          val nextValue = captureValue()
          result.add(nextValue)
          tryConsumeSpace()
          tryConsumeComma()
          tryConsumeSpace()
          if (nextTokenNameOrException() == PythonicTokenName.RIGHT_SQUARE_BRACKET) {
            moveToNextToken()
            break
          }
        }
        return result
      }

      PythonicTokenName.LEFT_CURLY_BRACKET -> {
        // object type
        val result = mutableMapOf<String, Any?>()
        while (true) {
          val keyToken = expectToken(PythonicTokenName.STRING_LITERAL)
          expectToken(PythonicTokenName.COLON)
          val value = captureValue()
          result.put(keyToken.text, value)
          tryConsumeSpace()
          tryConsumeComma()
          tryConsumeSpace()
          if (nextTokenNameOrException() == PythonicTokenName.RIGHT_CURLY_BRACKET) {
            moveToNextToken()
            break
          }
        }
        return result
      }
      else -> {
        throw PythonicSyntaxError(startPos, "Expect a value, but found $valueToken")
      }
    }
  }

  private fun nextTokenNameOrException(): PythonicTokenName {
    val tokenName = tokens.getOrNull(tokenPosition)?.name
    if (tokenName == null) {
      throw PythonicSyntaxError(tokenPosition, "Input ends while function call list is unfinished")
    }
    return tokenName
  }
}
