// src/ai/prompts/github.js
// Prompt template for GitHub Issues / PR descriptions output mode.
// Produces structured GitHub-flavoured Markdown with task lists and labels.

/** @typedef {import('../types.js').AIAnalysis} AIAnalysis */
/** @typedef {import('../types.js').LighthouseSummary} LighthouseSummary */

/**
 * Build a GitHub-issue-ready Markdown document from an AIAnalysis.
 *
 * @param {AIAnalysis} analysis
 * @param {LighthouseSummary} summary
 * @returns {string}
 */
export function buildGitHubPrompt(analysis, summary) {
  const date = new Date().toISOString().split('T')[0];

  return `## Performance Audit: ${summary.url}

> **Generated by Lighthouse Handoff** · ${date} · Strategy: ${summary.strategy.toUpperCase()}

### Summary

${analysis.executiveSummary}

---

### Priority Fixes

${analysis.priorityFixes.map((fix, i) => formatGitHubFix(fix, i + 1)).join('\n\n')}

---

### Quick Wins

${analysis.quickWins.map(w => `- [ ] ${w}`).join('\n')}

---

### Acceptance Criteria

${analysis.acceptanceCriteria.map(c => `- [ ] ${c}`).join('\n')}

---

### Labels

\`performance\` \`lighthouse\` \`core-web-vitals\`
`;
}

/**
 * @param {import('../types.js').PriorityFix} fix
 * @param {number} rank
 * @returns {string}
 */
function formatGitHubFix(fix, rank) {
  const steps = fix.instructions.map(step => `  - [ ] ${step}`).join('\n');
  return `#### ${rank}. ${fix.title}

${fix.reasoning}

**Steps:**
${steps}`;
}
