package ai.liquid.leap.function

import ai.liquid.leap.LeapJson
import ai.liquid.leap.LeapSerializationException
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.double
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import kotlinx.serialization.json.longOrNull
import kotlinx.serialization.json.put

/**
 * Describe a function call request generated by the model.
 *
 * Args:
 *
 * @param name the name of the function to be called
 * @param arguments the parameters of this call in a map. Values could be strings, numbers,
 *   booleans, arrays, nulls, or maps for objects.
 */
@Serializable(with = LeapFunctionCallSerializer::class)
data class LeapFunctionCall(val name: String, val arguments: Map<String, Any?>)

/** Sealed serializable representation of function argument values. */
@Serializable(with = FunctionArgSerializer::class)
sealed interface FunctionArg {
  companion object {
    fun fromJsonElement(element: JsonElement): FunctionArg =
      when (element) {
        is JsonNull -> LeapNull
        is JsonObject -> LeapObj(element.mapValues { fromJsonElement(it.value) })
        is JsonArray -> LeapArr(element.map { fromJsonElement(it) })
        is JsonPrimitive -> {
          when {
            element.isString -> LeapStr(element.content)
            element.booleanOrNull != null -> LeapBool(element.boolean)
            element.longOrNull != null -> {
              val longValue = element.long
              if (longValue in Int.MIN_VALUE..Int.MAX_VALUE) LeapNum.IntNum(longValue.toInt())
              else LeapNum.LongNum(longValue)
            }
            element.doubleOrNull != null -> LeapNum.DoubleNum(element.double)
            else -> LeapStr(element.content)
          }
        }
      }

    fun toJsonElement(value: FunctionArg): JsonElement =
      when (value) {
        is LeapNull -> JsonNull
        is LeapStr -> JsonPrimitive(value.value)
        is LeapBool -> JsonPrimitive(value.value)
        is LeapNum.IntNum -> JsonPrimitive(value.value)
        is LeapNum.LongNum -> JsonPrimitive(value.value)
        is LeapNum.DoubleNum -> JsonPrimitive(value.value)
        is LeapObj -> buildJsonObject { value.value.forEach { (k, v) -> put(k, toJsonElement(v)) } }
        is LeapArr -> buildJsonArray { value.value.forEach { add(toJsonElement(it)) } }
      }

    fun mapFromJsonObject(obj: JsonObject): Map<String, FunctionArg> =
      obj.mapValues { (_, v) -> fromJsonElement(v) }

    fun mapToJsonObject(map: Map<String, FunctionArg>): JsonObject = buildJsonObject {
      map.forEach { (k, v) -> put(k, toJsonElement(v)) }
    }

    fun mapFromAnyMap(map: Map<String, Any?>): Map<String, FunctionArg> =
      map.mapValues { (_, v) -> fromAny(v) }

    fun mapToAnyMap(map: Map<String, FunctionArg>): Map<String, Any?> =
      map.mapValues { (_, v) -> toAny(v) }

    fun fromAny(value: Any?): FunctionArg =
      when (value) {
        null -> LeapNull
        is FunctionArg -> value
        is String -> LeapStr(value)
        is Boolean -> LeapBool(value)
        is Int -> LeapNum.IntNum(value)
        is Short -> LeapNum.IntNum(value.toInt())
        is Byte -> LeapNum.IntNum(value.toInt())
        is Long -> LeapNum.LongNum(value)
        is Double -> LeapNum.DoubleNum(value)
        is Float -> LeapNum.DoubleNum(value.toDouble())
        is Map<*, *> -> {
          val m = mutableMapOf<String, FunctionArg>()
          value.forEach { (k, v) -> if (k is String) m[k] = fromAny(v) }
          LeapObj(m)
        }
        is List<*> -> LeapArr(value.map { fromAny(it) })
        is Array<*> -> LeapArr(value.map { fromAny(it) })
        else -> LeapStr(value.toString())
      }

    fun toAny(value: FunctionArg): Any? =
      when (value) {
        is LeapNull -> null
        is LeapStr -> value.value
        is LeapBool -> value.value
        is LeapNum.IntNum -> value.value
        is LeapNum.LongNum -> value.value
        is LeapNum.DoubleNum -> value.value
        is LeapObj -> value.value.mapValues { (_, v) -> toAny(v) }
        is LeapArr -> value.value.map { toAny(it) }
      }
  }
}

@Serializable data class LeapStr(val value: String) : FunctionArg

@Serializable data class LeapBool(val value: Boolean) : FunctionArg

@Serializable
sealed class LeapNum : FunctionArg {
  @Serializable data class IntNum(val value: Int) : LeapNum()

  @Serializable data class LongNum(val value: Long) : LeapNum()

  @Serializable data class DoubleNum(val value: Double) : LeapNum()
}

@Serializable data class LeapObj(val value: Map<String, FunctionArg>) : FunctionArg

@Serializable data class LeapArr(val value: List<FunctionArg>) : FunctionArg

@Serializable data object LeapNull : FunctionArg

object FunctionArgSerializer : KSerializer<FunctionArg> {
  override val descriptor: SerialDescriptor = JsonElement.serializer().descriptor

  override fun serialize(encoder: Encoder, value: FunctionArg) {
    val jsonEncoder =
      encoder as? JsonEncoder
        ?: throw SerializationException("FunctionArg can only be serialized to JSON")
    jsonEncoder.encodeJsonElement(FunctionArg.toJsonElement(value))
  }

  override fun deserialize(decoder: Decoder): FunctionArg {
    val jsonDecoder =
      decoder as? JsonDecoder
        ?: throw SerializationException("FunctionArg can only be deserialized from JSON")
    val elem = jsonDecoder.decodeJsonElement()
    return FunctionArg.fromJsonElement(elem)
  }
}

object LeapFunctionCallSerializer : KSerializer<LeapFunctionCall> {
  override val descriptor: SerialDescriptor = buildClassSerialDescriptor("LeapFunctionCall")

  override fun serialize(encoder: Encoder, value: LeapFunctionCall) {
    val jsonEncoder =
      encoder as? JsonEncoder
        ?: throw SerializationException("LeapFunctionCall can only be serialized to JSON")
    val obj = buildJsonObject {
      put("name", value.name)
      put("arguments", FunctionArg.mapToJsonObject(FunctionArg.mapFromAnyMap(value.arguments)))
    }
    jsonEncoder.encodeJsonElement(obj)
  }

  override fun deserialize(decoder: Decoder): LeapFunctionCall {
    val jsonDecoder =
      decoder as? JsonDecoder
        ?: throw SerializationException("LeapFunctionCall can only be deserialized from JSON")
    val elem = jsonDecoder.decodeJsonElement()
    val obj =
      elem as? JsonObject
        ?: throw SerializationException("Expected JsonObject for LeapFunctionCall")

    val name =
      obj["name"]?.jsonPrimitive?.content
        ?: throw LeapSerializationException("Function call name not found")

    val argsElem =
      obj["arguments"] ?: throw LeapSerializationException("Function call arguments not found")

    val argsObject: JsonObject =
      when (argsElem) {
        is JsonPrimitive -> {
          // Legacy encoded string case
          val argumentsObjJSON = argsElem.content
          LeapJson.parseToJsonElement(argumentsObjJSON).jsonObject
        }
        is JsonObject -> argsElem
        else -> throw LeapSerializationException("Invalid function call arguments format")
      }

    val arguments = FunctionArg.mapToAnyMap(FunctionArg.mapFromJsonObject(argsObject))
    return LeapFunctionCall(name, arguments)
  }
}
