package ai.liquid.leap.message

import ai.liquid.leap.LeapSerializationException
import ai.liquid.leap.function.LeapFunctionCall
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** A chat message in the chat history. */
@Serializable(with = ChatMessageJsonSerializer::class)
data class ChatMessage(
  /** The role of this message. */
  val role: Role,
  /** The list of contents of this message. */
  val content: List<ChatMessageContent>,
  /**
   * Reasoning content of this message. Reasoning content is only valid for messages generated by
   * the models.
   */
  @SerialName("reasoning_content") val reasoningContent: String? = null,
  /**
   * Function calls requested by the model. This field is only valid for models that support tool
   * calls.
   */
  @SerialName("tool_calls") val functionCalls: List<LeapFunctionCall>? = null,
) {
  /** Role of the message. */
  enum class Role(val type: String) {
    /** System prompt. It should only be used as the first message in a conversation. */
    SYSTEM("system"),

    /** User's prompt. It's the input from the user. */
    USER("user"),

    /** Assistant's response. It's the generated content from the model. */
    ASSISTANT("assistant"),

    // Tool response. It's the output from the tool. Model takes it as an input.
    TOOL("tool");

    companion object {
      /**
       * Create a Role value from a string literal.
       *
       * @param type string literal for the role value, compatible with OpenAI API.
       * @throws LeapSerializationException if the role string literal is not supported
       */
      fun fromTypeString(type: String): Role =
        when (type) {
          "system" -> SYSTEM
          "user" -> USER
          "assistant" -> ASSISTANT
          "tool" -> TOOL
          else -> {
            throw LeapSerializationException("Invalid role type: $type")
          }
        }
    }
  }

  /**
   * Single content constructor.
   *
   * @param role the role of this message
   * @param content the message content
   */
  constructor(role: Role, content: ChatMessageContent) : this(role, listOf(content), null)

  /**
   * Single text content constructor.
   *
   * @param role the role of this message
   * @param textContent the message text content
   */
  constructor(
    role: Role,
    textContent: String,
  ) : this(role, listOf(ChatMessageContent.Text(textContent)), null)
}
