package ai.liquid.leap.message

import ai.liquid.leap.function.LeapFunctionCall

enum class GenerationFinishReason {
  /** A stop token is generated by the model */
  STOP,

  /** The generated content exceeds the context window length */
  EXCEED_CONTEXT,

  /** The generation was interrupted on a user's request. */
  INTERRUPTED,

  /** Generation constraint requires the generation to stop. */
  CONSTRAINT,

  /** An error is thrown during the generation. */
  ERROR,
}

data class GenerationStats(
  /** Number of prompt tokens that were computed (excludes tokens restored from KV cache). */
  val promptTokens: Long,
  /** Number of tokens in the generated completion. */
  val completionTokens: Long,
  /** Total number of tokens used in the request (prompt + completion). */
  val totalTokens: Long,
  /** Average number of generated tokens per second during the whole generation. */
  val tokenPerSecond: Float,
  /** Number of prompt tokens restored from KV cache (not recomputed). */
  val cachedPromptTokens: Long = 0,
)

/** A piece of response from generation. */
sealed interface MessageResponse {
  /**
   * A chunk of generated output. The generation is still ongoing and its `text` field may contain
   * one or more tokens.
   */
  data class Chunk(val text: String) : MessageResponse

  /**
   * A chunk of generated reasoning content. The generation is still ongoing and its `reasoning`
   * field may contain one or more tokens. Reasoning content should not be considered as part of the
   * history, and it should be displayed separately.
   *
   * Only reasoning models should emit this chunk.
   */
  data class ReasoningChunk(val reasoning: String) : MessageResponse

  /** Parsed function call content. Only models that support function calls can emit this chunk. */
  data class FunctionCalls(val functionCalls: List<LeapFunctionCall>) : MessageResponse

  /** Audio content generated by the model. */
  data class AudioSample(val samples: FloatArray, val sampleRate: Int) : MessageResponse {
    override fun toString(): String =
      "AudioSample(sampleRate=$sampleRate, samplesSize=${samples.size})"

    override fun equals(other: Any?): Boolean {
      if (this === other) return true
      if (other == null || this::class != other::class) return false

      other as AudioSample

      if (sampleRate != other.sampleRate) return false
      if (!samples.contentEquals(other.samples)) return false

      return true
    }

    override fun hashCode(): Int = 31 * sampleRate + samples.contentHashCode()
  }

  /** Indicates the generation is done. */
  data class Complete(
    /** The complete message generated from this generation request. */
    val fullMessage: ChatMessage,
    /** The reason why generation finished. */
    val finishReason: GenerationFinishReason,
    /** Statistics about this generation like how many prompt tokens and completion tokens. */
    val stats: GenerationStats?,
  ) : MessageResponse
}
